/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jedi.netbeans;

import com.jedi.metadata.CustomTypeInfo;
import static com.jedi.metadata.DatabaseMetadataUtil.getProcedureCustomTypes;
import com.jedi.metadata.ProcedureMetadata;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.table.TableColumn;
import org.netbeans.api.db.explorer.DatabaseConnection;
import org.openide.util.Exceptions;

public final class CreationVisualPanel3 extends JPanel {

    private ProcedureMetadata procedure;

    /**
     * Creates new form CreationVisualPanel3
     */
    public CreationVisualPanel3() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Custom Type Mapping";
    }

    public void loadCustomTypes(ProcedureMetadata procedure) {
        this.procedure = procedure;
        DatabaseConnection databaseConnection = procedure.getDatabaseConnection();
        if (databaseConnection == null) {
            return;
        }

        try {
            Connection connection = databaseConnection.getJDBCConnection();
            procedure = getProcedureCustomTypes(connection, procedure);
            DefaultListModel model = new DefaultListModel();
            if (procedure.getCustomTypes() != null && !procedure.getCustomTypes().isEmpty()) {
                Set<String> customTypeNames = procedure.getCustomTypes().keySet();
                for (String customTypeName : customTypeNames) {
                    model.addElement(customTypeName);
                }

            }

            listCustomTypes.setModel(model);
            if (!model.isEmpty()) {
                listCustomTypes.setSelectedIndex(0);
            }

        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }

    }

    private void loadCustomTypeDetail() {
        if (procedure.getCustomTypes() == null || procedure.getCustomTypes().isEmpty()) {
            return;
        }

        String customTypeName = (String) listCustomTypes.getSelectedValue();
        CustomTypeInfo customTypeInfo = procedure.getCustomTypes().get(customTypeName);
        TableModelCustomTypeInfo model = new TableModelCustomTypeInfo(customTypeInfo);
        tableCustomTypeArguments.setModel(model);
        TableColumn fieldTypeColumn = tableCustomTypeArguments.getColumnModel().getColumn(3);
        String[] fieldTypes = {"String", "int", "long", "short", "float", "double", "BigDecimal", "byte", "byte[]", "boolean", "Date", "sql.Date", "sql.Time", "sql.Timestamp"};
        fieldTypeColumn.setCellEditor(new ArgumentFieldTypeCellEditor(fieldTypes));
        tableCustomTypeArguments.setRowHeight(25);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCustomTypes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCustomTypeArguments = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(null);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        listCustomTypes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listCustomTypes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCustomTypesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCustomTypes);

        tableCustomTypeArguments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCustomTypeArguments);
        if (tableCustomTypeArguments.getColumnModel().getColumnCount() > 0) {
            tableCustomTypeArguments.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.tableCustomTypeArguments.columnModel.title0")); // NOI18N
            tableCustomTypeArguments.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.tableCustomTypeArguments.columnModel.title1")); // NOI18N
            tableCustomTypeArguments.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.tableCustomTypeArguments.columnModel.title2")); // NOI18N
            tableCustomTypeArguments.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.tableCustomTypeArguments.columnModel.title3")); // NOI18N
        }

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jTextField1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jLabel2.text")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jedi/netbeans/search.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jButton1.text")); // NOI18N
        jButton1.setActionCommand(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jButton1.actionCommand")); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jedi/netbeans/add.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jButton2.text")); // NOI18N
        jButton2.setActionCommand(org.openide.util.NbBundle.getMessage(CreationVisualPanel3.class, "CreationVisualPanel3.jButton2.actionCommand")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(323, 323, 323)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listCustomTypesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCustomTypesValueChanged
        if (!evt.getValueIsAdjusting()) {
            loadCustomTypeDetail();
        }
    }//GEN-LAST:event_listCustomTypesValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList listCustomTypes;
    private javax.swing.JTable tableCustomTypeArguments;
    // End of variables declaration//GEN-END:variables
}
