/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jedi.netbeans;

import com.jedi.metadata.ArgumentMetadata;
import com.jedi.metadata.CustomTypeInfo;
import com.jedi.metadata.DatabaseMetadataUtil;
import com.jedi.metadata.ProcedureMetadata;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JPanel;
import javax.swing.table.TableColumn;
import org.openide.util.Exceptions;

public final class CustomTypeMappingVisualPanel1 extends JPanel {

    private ProcedureMetadata procedure;
    private ArgumentMetadata argument;

    public ProcedureMetadata getProcedure() {
        return procedure;
    }

    public void setProcedure(ProcedureMetadata procedure) {
        this.procedure = procedure;
    }

    public ArgumentMetadata getArgument() {
        return argument;
    }

    public void setArgument(ArgumentMetadata argument) {
        this.argument = argument;
    }

    /**
     * Creates new form CustomTypeMappingVisualPanel1
     */
    public CustomTypeMappingVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Custom Type Mapping";
    }

    public void loadCustomTypeInfo() {
        Connection connection = this.procedure.getDatabaseConnection().getJDBCConnection();
        try {
            CustomTypeInfo customTypeInfo = DatabaseMetadataUtil.getCustomType(connection, this.argument);
            CustomTypeInfoTableModel model = new CustomTypeInfoTableModel(customTypeInfo);
            tableArguments.setModel(model);
            TableColumn fieldTypeColumn = tableArguments.getColumnModel().getColumn(3);
            String[] fieldTypes = {"String", "int", "long", "short", "float", "double", "BigDecimal", "byte", "byte[]", "boolean", "Date", "sql.Date", "sql.Time", "sql.Timestamp"};
            fieldTypeColumn.setCellEditor(new ArgumentFieldTypeCellEditor(fieldTypes));
            TableColumn customTypeColumn = tableArguments.getColumnModel().getColumn(4);
            customTypeColumn.setPreferredWidth(30);
            customTypeColumn.setWidth(30);
            customTypeColumn.setMaxWidth(30);
            customTypeColumn.setMinWidth(30);

            customTypeColumn.setCellRenderer(new ArgumentCustomTypeCellRenderer());
            customTypeColumn.setCellEditor(new ArgumentCustomTypeCellEditor());
            tableArguments.setRowHeight(25);

        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArguments = new javax.swing.JTable();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CustomTypeMappingVisualPanel1.class, "CustomTypeMappingVisualPanel1.jLabel1.text")); // NOI18N

        tableArguments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableArguments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableArguments;
    // End of variables declaration//GEN-END:variables
}
